export const TEMP_DIR_NAME = 'temp';
export const FILENAME = 'Orders';

export const EXCEL_HEADERS = [
  'ID',
  'Status',
  'Created on',
  'Price includes taxes?',
  'Discounts total',
  'Shipping total',
  'Total',
  'Total with taxes',
  'Payment method',
  'Transaction ID',
  'Payment date',
  'Products',
  'Billing: First name',
  'Billing: Last name',
  'Billing: Company',
  'Billing: Address #1',
  'Billing: Address #2',
  'Billing: City',
  'Billing: State',
  'Billing: Postal code',
  'Billing: Email',
  'Billing: Phone',
  'Shipping: First name',
  'Shipping: Last name',
  'Shipping: Company',
  'Shipping: Address #1',
  'Shipping: Address #2',
  'Shipping: City',
  'Shipping: State',
  'Shipping: Postal code',
  'Shipping: Phone',
];
